### ISSUE TITLE
scraper vyzera prestal fungovat

### ISSUE THREAD

**Issue by hanecak** [soit-sk/patenty_-_upv#1]
Posledne dva behy scrapra na Morph.io skoncili chybou (vid hnede vypisy v casi "History"). Ostany vystup konzoli hlasil vela error/timeout a nasledne hlasenie od Morph.io, ze teda scraper bezi viac ako den a teda bol nasilne ukonceny.

Poprosim teda preverit, ci scraper nadalej funguje ako ma.

**Comment by katkad** [comment]
funguje:
1 record added, 1 record removed in the database
131905 pages scraped
